server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: taskuser
    password: taskpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    drop-first: false
    default-schema: public
    liquibase-schema: public
    change-log: classpath:changelog/data/db/changelog/database-changelog.xml

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    sender:
      email: ${MAIL_SENDER_EMAIL}
      text: no-reply

captcha:
  expiration: PT5M
  checkDelay: PT1M

security:
  oauth2:
    resourceserver:
      jwt:
        jwk-set-uri: ${JWT_JWK_SET_URI}

access-token:
  private: access-refresh-token-keys/access-token-private.key
  public: access-refresh-token-keys/access-token-public.key
refresh-token:
  private: access-refresh-token-keys/refresh-token-private.key
  public: access-refresh-token-keys/refresh-token-public.key
